<Project>
  <PropertyGroup>
    <Version>0.1.0-beta</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <Authors>Gregor Maher</Authors>
    <Product>G CET Runtime Profiler</Product>
    <RepositoryUrl>https://github.com/giorgioherma/G-CET_Runtime_Profiler</RepositoryUrl>
  </PropertyGroup>
</Project>
