<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <AssemblyName>G-CET-Cadence-Resolver</AssemblyName>
    <RootNamespace>GCETRuntimeProfiler.Resolver</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\G.CETProfiler.Core\G.CETProfiler.Core.csproj" />
  </ItemGroup>
</Project>
